imports = [ "git.hooks" ]

[devshell]
packages = [
  "git-crypt"
]

[[env]]
name = "NIX_CONFIG"
value = """\
extra-experimental-features = nix-command flakes ca-references
extra-substituters = https://nrdxp.cachix.org https://nix-community.cachix.org
extra-trusted-public-keys = nrdxp.cachix.org-1:Fc5PSqY2Jm1TrWfm88l6cvGWwz3s93c6IOifQWnhNW4= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=\
"""

[[commands]]
package = "git"
category = "vcs"

[[commands]]
package = "nixpkgs-fmt"
category = "linters"

[[commands]]
package = "editorconfig-checker"
category = "linters"

[[commands]]
package = "python3Packages.grip"
category = "documentation"

[[commands]]
package = "mdbook"
category = "documentation"

[[commands]]
name = "ssh-show-ed25519"
category = "secrets"
command = '''
          user="$(cut -d ';' -f 1 <<< "$1")"
          if [[ "$user" == "root" ]]; then
          ssh $1 "cat /etc/ssh/ssh_host_ed25519_key.pub"
          else
          ssh $1 "cat ~/.ssh/id_ed25519.pub"
          fi
        '''
help = "ssh-show-ed25519 <user@hostName> | Show target host's SSH ed25519 key"

[git.hooks]
enable = true
